DROP DATABASE IF EXISTS Business;
CREATE DATABASE IF NOT EXISTS Business DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE Business;

CREATE TABLE IF NOT EXISTS Role (
  RoleId SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(64) NOT NULL,
  CreatedBy MEDIUMINT UNSIGNED NOT NULL,
  CreatedDate DATETIME DEFAULT NOW(),
  LastModifiedBy MEDIUMINT UNSIGNED NOT NULL,
  LastModifiedDate DATETIME NOT NULL,

  CONSTRAINT RoleCreatedByFk
  FOREIGN KEY (CreatedBy)
  REFERENCES User(UserId),

  CONSTRAINT RoleLastModifiedByFk
  FOREIGN KEY (LastModifiedBy)
  REFERENCES User(UserId)
);

CREATE TABLE IF NOT EXISTS Branch (
  BranchId SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(128) NOT NULL,
  CreatedBy MEDIUMINT UNSIGNED NOT NULL,
  CreatedDate DATETIME DEFAULT NOW(),
  LastModifiedBy MEDIUMINT UNSIGNED NOT NULL,
  LastModifiedDate DATETIME NOT NULL,

  CONSTRAINT BranchCreatedByFk
  FOREIGN KEY (CreatedBy)
  REFERENCES User(UserId),

  CONSTRAINT BranchLastModifiedByFk
  FOREIGN KEY (LastModifiedBy)
  REFERENCES User(UserId)
);

CREATE TABLE IF NOT EXISTS User (
  UserId MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  RoleId SMALLINT UNSIGNED NOT NULL,
  BranchId SMALLINT UNSIGNED NOT NULL,
  FirstName VARCHAR(128) NOT NULL,
  MiddleName VARCHAR(128) DEFAULT NULL,
  SurNames VARCHAR(255) DEFAULT NULL,
  Email VARCHAR(128) NOT NULL UNIQUE,
  PhoneNumber VARCHAR(32) DEFAULT NULL,
  Street VARCHAR(255) DEFAULT NULL,
  ExteriorNumber VARCHAR(32) DEFAULT NULL,
  InteriorNumber VARCHAR(32) DEFAULT NULL,
  Neighborhood VARCHAR(64) DEFAULT NULL,
  PostalCode MEDIUMINT UNSIGNED DEFAULT NULL,
  UserName VARCHAR(16) NOT NULL,
  Password TINYBLOB NOT NULL,
  Status BOOLEAN DEFAULT TRUE,
  CreatedBy MEDIUMINT UNSIGNED NOT NULL,
  CreatedDate DATETIME DEFAULT NOW(),
  LastModifiedBy MEDIUMINT UNSIGNED NOT NULL,
  LastModifiedDate DATETIME NOT NULL

  CONSTRAINT UserRolFk
  FOREIGN KEY (RoleId)
  REFERENCES Role(RoleId),

  CONSTRAINT UserBranchFk
  FOREIGN KEY (BranchId)
  REFERENCES Branch(BranchId),

  CONSTRAINT UserCreatedByFk
  FOREIGN KEY (CreatedBy)
  REFERENCES User(UserId),

  CONSTRAINT UserLastModifiedByFk
  FOREIGN KEY (LastModifiedBy)
  REFERENCES User(UserId)
);

CREATE TABLE IF NOT EXISTS Permission (
  PermissionId MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMEN PRIMARY KEY
  Name VARCHAR(64) NOT NULL,
  ParentPermission INT UNSIGNED DEFAULT NULL,
  CreatedBy MEDIUMINT UNSIGNED NOT NULL,
  CreatedDate DATETIME DEFAULT NOW(),
  LastModifiedBy MEDIUMINT UNSIGNED NOT NULL,
  LastModifiedDate DATETIME NOT NULL,

  CONSTRAINT PermissionCreatedByFk
  FOREIGN KEY (CreatedBy)
  REFERENCES User(UserId),

  CONSTRAINT PermissionLastModifiedByFk
  FOREIGN KEY (LastModifiedBy)
  REFERENCES User(UserId)
)

CREATE TABLE IF NOT EXISTS UserPermission (
  UserPermissionId INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  PermissionId INT UNSIGNED NOT NULL,
  CreatedBy MEDIUMINT UNSIGNED NOT NULL,
  CreatedDate DATETIME DEFAULT NOW(),
  LastModifiedBy MEDIUMINT UNSIGNED NOT NULL,
  LastModifiedDate DATETIME NOT NULL,

  CONSTRAINT UserPermissionPermissionFk
  FOREIGN KEY (PermissionId)
  REFERENCES Permission(PermissionId),

  CONSTRAINT UserPermissionCreatedByFk
  FOREIGN KEY (CreatedBy)
  REFERENCES User(UserId),

  CONSTRAINT UserPermissionLastModifiedByFk
  FOREIGN KEY (LastModifiedBy)
  REFERENCES User(UserId)
)

CREATE TABLE IF NOT EXISTS Token (
  TokenId INT UNSIGNED NOT NULL PRIMARY KEY,
  Value VARCHAR(510) NOT NULL,
  ExperationDate DATETIME NOT NULL,
  CreatedDate DATETIME DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS Category (
  CategoryId MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(255) DEFAULT NULL,
  CreatedBy MEDIUMINT UNSIGNED NOT NULL,
  CreatedDate DATETIME DEFAULT NOW(),
  LastModifiedBy MEDIUMINT UNSIGNED NOT NULL,
  LastModifiedDate DATETIME NOT NULL,

  CONSTRAINT CategoryCreatedByFk
  FOREIGN KEY (CreatedBy)
  REFERENCES User(UserId),

  CONSTRAINT CategoryLastModifiedByFk
  FOREIGN KEY (LastModifiedBy)
  REFERENCES User(UserId)
);

CREATE TABLE IF NOT EXISTS SubCategory (
  SubCategoryId MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(255) DEFAULT NULL,
  CreatedBy MEDIUMINT UNSIGNED NOT NULL,
  CreatedDate DATETIME DEFAULT NOW(),
  LastModifiedBy MEDIUMINT UNSIGNED NOT NULL,
  LastModifiedDate DATETIME NOT NULL,

  CONSTRAINT SubCategoryCreatedByFk
  FOREIGN KEY (CreatedBy)
  REFERENCES User(UserId),

  CONSTRAINT SubCategoryLastModifiedByFk
  FOREIGN KEY (LastModifiedBy)
  REFERENCES User(UserId)
);

CREATE TABLE IF NOT EXISTS CategorySubCategory (
  CategorySubCategoryId INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CategoryId INT UNSIGNED NOT NULL,
  SubCategoryId INT UNSIGNED NOT NULL,
  CreatedBy MEDIUMINT UNSIGNED NOT NULL,
  CreatedDate DATETIME DEFAULT NOW(),
  LastModifiedBy MEDIUMINT UNSIGNED NOT NULL,
  LastModifiedDate DATETIME NOT NULL,

  CONSTRAINT CategorySubCategoryCategoryFk
  FOREIGN KEY (CategoryId) 
  REFERENCES Category(CategoryId),

  CONSTRAINT CategorySubCategorySubCategoryFk
  FOREIGN KEY (SubCategoryId)
  REFERENCES SubCategory(SubCategoryId),

  CONSTRAINT CategorySubCategoryCreatedByFk
  FOREIGN KEY (CreatedBy)
  REFERENCES User(UserId),

  CONSTRAINT CategorySubCategoryLastModifiedByFk
  FOREIGN KEY (LastModifiedBy)
  REFERENCES User(UserId)
);

CREATE TABLE IF NOT EXISTS MeasurementUnit (
  MeasurementUnitId TINYINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  key VARCHAR(16) DEFAULT NULL,
  Name VARCHAR(64) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS Discount (
  DiscountId TINYINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Quantity DECIMAL(10,2) NOT NULL,
  CreatedBy MEDIUMINT UNSIGNED NOT NULL,
  CreatedDate DATETIME DEFAULT NOW(),
  LastModifiedBy MEDIUMINT UNSIGNED NOT NULL,
  LastModifiedDate DATETIME NOT NULL,

  CONSTRAINT DiscountCreatedByFk
  FOREIGN KEY (CreatedBy)
  REFERENCES User(UserId),

  CONSTRAINT DiscountLastModifiedByFk
  FOREIGN KEY (LastModifiedBy)
  REFERENCES User(UserId)
);

CREATE TABLE IF NOT EXISTS Product (
  ProductId INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MeasurementUnitId SMALLINT UNSIGNED NOT NULL,
  Name VARCHAR(128) DEFAULT NULL,
  Description VARCHAR(255) DEFAULT NULL,
  CreatedBy MEDIUMINT UNSIGNED NOT NULL,
  CreatedDate DATETIME DEFAULT NOW(),
  LastModifiedBy MEDIUMINT UNSIGNED NOT NULL,
  LastModifiedDate DATETIME NOT NULL,

  CONSTRAINT ProductMeasurementUnitFk
  FOREIGN KEY (MeasurementUnitId)
  REFERENCES MeasurementUnit(MeasurementUnitId),

  CONSTRAINT ProductCreatedByFk
  FOREIGN KEY (CreatedBy)
  REFERENCES User(UserId),

  CONSTRAINT ProductLastModifiedByFk
  FOREIGN KEY (LastModifiedBy)
  REFERENCES User(UserId)
);

CREATE TABLE MeasurementUnitEquivalence (
  MeasurementUnitEquivalenceId MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ProductId INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Equivalence TINYINT UNSIGNED NOT NULL COMMENT 'Measurement unit id',
  Quantity SMALLINT UNSIGNED NOT NULL,
  CreatedBy MEDIUMINT UNSIGNED NOT NULL,
  CreatedDate DATETIME DEFAULT NOW(),
  LastModifiedBy MEDIUMINT UNSIGNED NOT NULL,
  LastModifiedDate DATETIME NOT NULL,

  CONSTRAINT MeasurementUnitEquivalenceProductFk
  FOREIGN KEY (ProductId)
  REFERENCES Product(ProductId),

  CONSTRAINT MeasurementUnitEquivalenceEquivalenceFk
  FOREIGN KEY (Equivalence)
  REFERENCES MeasurementUnit(MeasurementUnitId),

  CONSTRAINT MeasurementUnitEquivalenceCreatedByFk
  FOREIGN KEY (CreatedBy)
  REFERENCES User(UserId),

  CONSTRAINT MeasurementUnitEquivalenceLastModifiedByFk
  FOREIGN KEY (LastModifiedBy)
  REFERENCES User(UserId)
);

CREATE TABLE ImageUrl (
  ImageUrlId INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ImageUrl VARCHAR(500) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS ProductImageUrl (
  ProductImageUrlId INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ProductId INT UNSIGNED NOT NULL,
  ImageUrlId INT UNSIGNED NOT NULL,

  CONSTRAINT ProductImageUrlProductFk
  FOREIGN KEY (ProductId)
  REFERENCES Product(ProductId)

  CONSTRAINT ProductImageUrlImageUrlFk
  FOREIGN KEY (ImageUrlId)
  REFERENCES ImageUrl(ImageUrlId)
)

CREATE TABLE IF NOT EXISTS ProductCategory (
  ProductCategoryId INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ProductId INT UNSIGNED NOT NULL,
  CategoryId INT UNSIGNED NOT NULL,
  CreatedBy MEDIUMINT UNSIGNED NOT NULL,
  CreatedDate DATETIME DEFAULT NOW(),
  LastModifiedBy MEDIUMINT UNSIGNED NOT NULL,
  LastModifiedDate DATETIME NOT NULL,

  CONSTRAINT ProductCategoryProductFk
  FOREIGN KEY (ProductId)
  REFERENCES Product(ProductId),

  CONSTRAINT ProductCategoryCategoryFk
  FOREIGN KEY (CategoryId)
  REFERENCES Category(CategoryId),

  CONSTRAINT ProductCategoryCreatedByFk
  FOREIGN KEY (CreatedBy)
  REFERENCES User(UserId),

  CONSTRAINT ProductCategoryLastModifiedByFk
  FOREIGN KEY (LastModifiedBy)
  REFERENCES User(UserId)
);

CREATE TABLE IF NOT EXISTS BranchProduct (
  BranchProduct INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  BranchId SMALLINT UNSIGNED NOT NULL,
  ProductId INT UNSIGNED NOT NULL,
  DiscountId TINYINT UNSIGNED DEFAULT NULL,
  Stock DECIMAL(10,2) NOT NULL,
  SellPrice DECIMAL(10,2) NOT NULL,
  PriceUpdated DATETIME DEFAULT NOW(),
  Utility DECIMAL(10,2) NOT NULL,
  CreatedBy MEDIUMINT UNSIGNED NOT NULL,
  CreatedDate DATETIME DEFAULT NOW(),
  LastModifiedBy MEDIUMINT UNSIGNED NOT NULL,
  LastModifiedDate DATETIME NOT NULL,
  
  CONSTRAINT BranchProductBranchFk
  FOREIGN KEY (BranchId)
  REFERENCES Branch(BranchId),

  CONSTRAINT BranchProductProductFk
  FOREIGN KEY (ProductId)
  REFERENCES Product(ProductId),

  CONSTRAINT BranchProductDiscountFk
  FOREIGN KEY (DiscountId)
  REFERENCES Discount(DiscountId),

  CONSTRAINT BranchProductCreatedByFk
  FOREIGN KEY (CreatedBy)
  REFERENCES User(UserId),

  CONSTRAINT BranchProductLastModifiedByFk
  FOREIGN KEY (LastModifiedBy)
  REFERENCES User(UserId)
);

CREATE TABLE IF NOT EXISTS BranchProductHistory (
  BranchProductHistoryId MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  BranchProductId INT UNSIGNED NOT NULL,
  SellPrice DECIMAL(10,2) NOT NULL,
  Utility DECIMAL(10,2) NOT NULL,
  CreatedBy MEDIUMINT UNSIGNED NOT NULL,
  CreatedDate DATETIME DEFAULT NOW(),
  LastModifiedBy MEDIUMINT UNSIGNED NOT NULL,
  LastModifiedDate DATETIME NOT NULL,
  
  CONSTRAINT BranchProductHistoryBranchProductFk
  FOREIGN KEY (BranchProductId)
  REFERENCES BranchProduct(BranchProductId),

  CONSTRAINT BranchProductHistoryCreatedByFk
  FOREIGN KEY (CreatedBy)
  REFERENCES User(UserId),

  CONSTRAINT BranchProductHistoryLastModifiedByFk
  FOREIGN KEY (LastModifiedBy)
  REFERENCES User(UserId)
);

CREATE TABLE IF NOT EXISTS FiscalClient (
  FiscalClientId INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  KindOfPerson VARCHAR(32) NOT NULL,
  RFC VARCHAR(32) NOT NULL UNIQUE,
  BusinessName VARCHAR(510) NOT NULL,
  TradingName VARCHAR(510) NOT NULL,
  Email VARCHAR(128) NOT NULL UNIQUE,
  Street VARCHAR(255) NOT NULL,
  ExteriorNumber VARCHAR(32) NOT NULL,
  InteriorNumber VARCHAR(32) NOT NULL,
  Neighborhood VARCHAR(64) NOT NULL,
  PostalCode MEDIUMINT UNSIGNED NOT NULL,
  PhoneNumber VARCHAR(32) DEFAULT NULL,
  Town VARCHAR(128) NOT NULL,
  State VARCHAR(128) NOT NULL,
  CreatedBy MEDIUMINT UNSIGNED NOT NULL,
  CreatedDate DATETIME DEFAULT NOW(),
  LastModifiedBy MEDIUMINT UNSIGNED NOT NULL,
  LastModifiedDate DATETIME NOT NULL,

  CONSTRAINT FiscalClientCreatedByFk
  FOREIGN KEY (CreatedBy)
  REFERENCES User(UserId),

  CONSTRAINT FiscalClientLastModifiedByFk
  FOREIGN KEY (LastModifiedBy)
  REFERENCES User(UserId)
);

CREATE TABLE IF NOT EXISTS Client (
  ClientId INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  BranchId SMALLINT UNSIGNED NOT NULL,
  FiscalClientId INT UNSIGNED DEFAULT NULL,
  FirstName VARCHAR(128) NOT NULL,
  MiddleName VARCHAR(128) DEFAULT NULL,
  SurNames VARCHAR(255) DEFAULT NULL,
  Email VARCHAR(128) DEFAULT NULL UNIQUE,
  LandLine VARCHAR(32) DEFAULT NULL,
  MobilePhone VARCHAR(32) DEFAULT NULL,
  CreatedBy MEDIUMINT UNSIGNED NOT NULL,
  CreatedDate DATETIME DEFAULT NOW(),
  LastModifiedBy MEDIUMINT UNSIGNED NOT NULL,
  LastModifiedDate DATETIME NOT NULL,

  CONSTRAINT ClientBranchFk
  FOREIGN KEY (BranchId)
  REFERENCES Branch(BranchId),

  CONSTRAINT ClientFiscalClientFk
  FOREIGN KEY (FiscalClientId)
  REFERENCES FiscalClient(FiscalClientId),

  CONSTRAINT ClientCreatedByFk
  FOREIGN KEY (CreatedBy)
  REFERENCES User(UserId),

  CONSTRAINT ClientLastModifiedByFk
  FOREIGN KEY (LastModifiedBy)
  REFERENCES User(UserId)
);

CREATE TABLE IF NOT EXISTS Sale (
  SaleId INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ClientId INT UNSIGNED DEFAULT NULL,
  TransactionNumber INT UNSIGNED NOT NULL UNIQUE,
  IVA DECIMAL(20, 2) NOT NULL,
  SubTotal DECIMAL(20, 2) NOT NULL,
  Total DECIMAL(20, 2) NOT NULL,
  QuantityItems MEDIUMINT UNSIGNED NOT NULL,
  Status VARCHAR(64) COMMENT 'pending || closed',
  Type VARCHAR(16) NOT NULL COMMENT 'sale || order',
  CreatedBy MEDIUMINT UNSIGNED NOT NULL,
  CreatedDate DATETIME DEFAULT NOW(),
  LastModifiedBy MEDIUMINT UNSIGNED NOT NULL,
  LastModifiedDate DATETIME NOT NULL,

  CONSTRAINT SaleClientFk
  FOREIGN KEY (ClientId)
  REFERENCES Client(ClientId),

  CONSTRAINT SaleCreatedByFk
  FOREIGN KEY (CreatedBy)
  REFERENCES User(UserId),

  CONSTRAINT SaleLastModifiedByFk
  FOREIGN KEY (LastModifiedBy)
  REFERENCES User(UserId)
);

CREATE TABLE IF NOT EXISTS SaleDetail (
  SaleDetailId INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  SaleId INT UNSIGNED NOT NULL,
  ProductId INT UNSIGNED NOT NULL,
  IVA DECIMAL(20, 2) NOT NULL,
  SubTotal DECIMAL(20, 2) NOT NULL,
  TotaL DECIMAL(20, 2) NOT NULL,

  CONSTRAINT SaleDetailSaleFk
  FOREIGN KEY (SaleId)
  REFERENCES Sale(SaleId),

  CONSTRAINT SaleDetailProductFk
  FOREIGN KEY (ProductId)
  REFERENCES Product(ProductId)
);

CREATE TABLE IF NOT EXISTS Vendor (
  VendorId SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  BusinessName VARCHAR(510) NOT NULL,
  TradingName VARCHAR(510) NOT NULL,
  KindOfPerson VARCHAR(32) NOT NULL,
  RFC VARCHAR(32) NOT NULL UNIQUE,
  PhoneNumber VARCHAR(32) DEFAULT NULL,
  Email VARCHAR(128) DEFAULT NULL UNIQUE,
  Street VARCHAR(255) DEFAULT NULL,
  ExteriorNumber VARCHAR(32) DEFAULT NULL,
  InteriorNumber VARCHAR(32) DEFAULT NULL,
  Neighborhood VARCHAR(64) DEFAULT NULL,
  PostalCode MEDIUMINT UNSIGNED DEFAULT NULL,
  CreatedBy MEDIUMINT UNSIGNED NOT NULL,
  CreatedDate DATETIME DEFAULT NOW(),
  LastModifiedBy MEDIUMINT UNSIGNED NOT NULL,
  LastModifiedDate DATETIME NOT NULL,

  CONSTRAINT VendorCreatedByFk
  FOREIGN KEY (CreatedBy)
  REFERENCES User(UserId),

  CONSTRAINT VendorLastModifiedByFk
  FOREIGN KEY (LastModifiedBy)
  REFERENCES User(UserId)
);

CREATE TABLE IF NOT EXISTS BranchVendor (
  BranchVendorId INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  BranchId SMALLINT UNSIGNED NOT NULL,
  VendorId SMALLINT UNSIGNED NOT NULL,
  CreatedBy MEDIUMINT UNSIGNED NOT NULL,
  CreatedDate DATETIME DEFAULT NOW(),
  LastModifiedBy MEDIUMINT UNSIGNED NOT NULL,
  LastModifiedDate DATETIME NOT NULL,
  
  CONSTRAINT BranchVendorBranchFk
  FOREIGN KEY (BranchId)
  REFERENCES Branch(BranchId),

  CONSTRAINT BranchVendorProviderFk
  FOREIGN KEY (VendorId)
  REFERENCES Vendor(VendorId),

  CONSTRAINT BranchVendorCreatedByFk
  FOREIGN KEY (CreatedBy)
  REFERENCES User(UserId),

  CONSTRAINT BranchVendorLastModifiedByFk
  FOREIGN KEY (LastModifiedBy)
  REFERENCES User(UserId)
);

CREATE TABLE IF NOT EXISTS VendorProduct (
  VendorProductId INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  VendorId SMALLINT UNSIGNED NOT NULL,
  ProductId INT UNSIGNED NOT NULL,
  SellPrice DECIMAL(10,2) NOT NULL,
  QuantityPerUnit DECIMAL(10, 2) DEFAULT NULL,
  SKU VARCHAR(128) DEFAULT NULL,
  CreatedBy MEDIUMINT UNSIGNED NOT NULL,
  CreatedDate DATETIME DEFAULT NOW(),
  LastModifiedBy MEDIUMINT UNSIGNED NOT NULL,
  LastModifiedDate DATETIME NOT NULL,
  
  CONSTRAINT VendorProductVendorFk
  FOREIGN KEY (VendorId)
  REFERENCES Vendor(VendorId),

  CONSTRAINT VendorProductProductFk
  FOREIGN KEY (ProductId)
  REFERENCES Product(ProductId),

  CONSTRAINT VendorProductCreatedByFk
  FOREIGN KEY (CreatedBy)
  REFERENCES User(UserId),

  CONSTRAINT VendorProductLastModifiedByFk
  FOREIGN KEY (LastModifiedBy)
  REFERENCES User(UserId)
);

CREATE TABLE IF NOT EXISTS VendorProductHistory (
  VendorProductHistoryId INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  VendorProductId INT UNSIGNED NOT NULL,
  SellPrice DECIMAL(10,2) NOT NULL,
  PriceUpdated DATETIME DEFAULT NOW(),
  CreatedBy MEDIUMINT UNSIGNED NOT NULL,
  CreatedDate DATETIME DEFAULT NOW(),
  LastModifiedBy MEDIUMINT UNSIGNED NOT NULL,
  LastModifiedDate DATETIME NOT NULL,
  
  CONSTRAINT VendorProductHistoryVendorProductFk
  FOREIGN KEY (VendorProductId)
  REFERENCES VendorProduct(VendorProductId),

  CONSTRAINT VendorProductHistoryCreatedByFk
  FOREIGN KEY (CreatedBy)
  REFERENCES User(UserId),

  CONSTRAINT VendorProductHistoryLastModifiedByFk
  FOREIGN KEY (LastModifiedBy)
  REFERENCES User(UserId)
);

CREATE TABLE IF NOT EXISTS VendorContact (
  VendorContactId INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  VendorId INT UNSIGNED NOT NULL,
  FirstName VARCHAR(128) NOT NULL,
  MiddleName VARCHAR(128) DEFAULT NULL,
  SurNames VARCHAR(255) DEFAULT NULL,
  PhoneNumber VARCHAR(32) DEFAULT NULL,
  Email VARCHAR(128) DEFAULT NULL UNIQUE,
  Position VARCHAR(64) DEFAULT NULL,
  CreatedBy MEDIUMINT UNSIGNED NOT NULL,
  CreatedDate DATETIME DEFAULT NOW(),
  LastModifiedBy MEDIUMINT UNSIGNED NOT NULL,
  LastModifiedDate DATETIME NOT NULL,
  
  CONSTRAINT VendorContactVendorFk
  FOREIGN KEY (VendorId)
  REFERENCES Vendor(VendorId),

  CONSTRAINT VendorContactCreatedByFk
  FOREIGN KEY (CreatedBy)
  REFERENCES User(UserId),

  CONSTRAINT VendorContactLastModifiedByFk
  FOREIGN KEY (LastModifiedBy)
  REFERENCES User(UserId)
);

CREATE TABLE IF NOT EXISTS VendorBank (
  VendorBankId INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  VendorId INT UNSIGNED NOT NULL,
  Name VARCHAR(255) NOT NULL,
  AccountNumber VARCHAR(128) NOT NULL,
  Clabe BIGINT UNSIGNED NOT NULL,
  AccountHolder VARCHAR(128) NOT NULL,
  CreatedBy MEDIUMINT UNSIGNED NOT NULL,
  CreatedDate DATETIME DEFAULT NOW(),
  LastModifiedBy MEDIUMINT UNSIGNED NOT NULL,
  LastModifiedDate DATETIME NOT NULL,
  
  CONSTRAINT VendorBankVendorFk
  FOREIGN KEY (VendorId)
  REFERENCES Vendor(VendorId),

  CONSTRAINT VendorBankCreatedByFk
  FOREIGN KEY (CreatedBy)
  REFERENCES User(UserId),

  CONSTRAINT VendorBankLastModifiedByFk
  FOREIGN KEY (LastModifiedBy)
  REFERENCES User(UserId)
);

CREATE TABLE IF NOT EXISTS Order (
  OrderId INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  VendorId INT UNSIGNED NOT NULL,
  IVA DECIMAL(20, 2) NOT NULL,
  SubTotal DECIMAL(20, 2) NOT NULL,
  TotaL DECIMAL(20, 2) NOT NULL,
  QuantityItems MEDIUMINT UNSIGNED NOT NULL,
  CreatedBy MEDIUMINT UNSIGNED NOT NULL,
  CreatedDate DATETIME DEFAULT NOW(),
  LastModifiedBy MEDIUMINT UNSIGNED NOT NULL,
  LastModifiedDate DATETIME NOT NULL,

  CONSTRAINT OrderVendorFk
  FOREIGN KEY (VendorId)
  REFERENCES Vendor(VendorId),

  CONSTRAINT OrderCreatedByFk
  FOREIGN KEY (CreatedBy)
  REFERENCES User(UserId),

  CONSTRAINT OrderLastModifiedByFk
  FOREIGN KEY (LastModifiedBy)
  REFERENCES User(UserId)
);

CREATE TABLE IF NOT EXISTS OrderDetail (
  OrderDetailId INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  OrderId INT UNSIGNED NOT NULL,
  ProductId INT UNSIGNED NOT NULL,
  IVA DECIMAL(20, 2) NOT NULL,
  SubTotal DECIMAL(20, 2) NOT NULL,
  Total DECIMAL(20, 2) NOT NULL,
  
  CONSTRAINT OrderDetailOrderFk
  FOREIGN KEY (OrderId)
  REFERENCES Order(OrderId),

  CONSTRAINT OrderDetailProductFk
  FOREIGN KEY (ProductId)
  REFERENCES Product(ProductId)
);

CREATE TABLE IF NOT EXISTS Refund (
  RefundId INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  SaleId INT UNSIGNED NOT NULL,
  Total DECIMAL(20, 2) NOT NULL,
  QuantityItems MEDIUMINT UNSIGNED NOT NULL,
  Reason VARCHAR(510) NOT NULL,
  CreatedBy MEDIUMINT UNSIGNED NOT NULL,
  CreatedDate DATETIME DEFAULT NOW(),
  LastModifiedBy MEDIUMINT UNSIGNED NOT NULL,
  LastModifiedDate DATETIME NOT NULL,

  CONSTRAINT RefundSaleFk
  FOREIGN KEY (SaleId)
  REFERENCES Sale(SaleId),

  CONSTRAINT RefundCreatedByFk
  FOREIGN KEY (CreatedBy)
  REFERENCES User(UserId),

  CONSTRAINT RefundLastModifiedByFk
  FOREIGN KEY (LastModifiedBy)
  REFERENCES User(UserId)
);

CREATE TABLE IF NOT EXISTS RefundDetail (
  RefundDetailId INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  RefundId INT UNSIGNED NOT NULL,
  ProductId INT UNSIGNED NOT NULL,
  
  CONSTRAINT RefundDetailRefundFk
  FOREIGN KEY (RefundId)
  REFERENCES Refund(RefundId),
  
  CONSTRAINT RefundDetailProductFk
  FOREIGN KEY (ProductId)
  REFERENCES Product(ProductId)
);

CREATE TABLE IF NOT EXISTS ExpenseType (
  ExpenseTypeId INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Type VARCHAR(64) COMMENT 'DECREASE || CONSUMABLE',
);

CREATE TABLE IF NOT EXISTS ProductExpense (
  ProductExpenseId INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ProductId INT UNSIGNED NOT NULL,
  ExpenseTypeId INT UNSIGNED NOT NULL,
  Reason VARCHAR(510),
  CreatedBy MEDIUMINT UNSIGNED NOT NULL,
  CreatedDate DATETIME DEFAULT NOW(),
  LastModifiedBy MEDIUMINT UNSIGNED NOT NULL,
  LastModifiedDate DATETIME NOT NULL,

  CONSTRAINT ProductExpenseProductFk
  FOREIGN KEY (ProductId)
  REFERENCES Product(ProductId),

  CONSTRAINT ProductExpenseExpenseType
  FOREIGN KEY (ExpenseTypeId)
  REFERENCES ExpenseType(ExpenseTypeId),

  CONSTRAINT ProductExpenseCreatedByFk
  FOREIGN KEY (CreatedBy)
  REFERENCES User(UserId),

  CONSTRAINT ProductExpenseLastModifiedByFk
  FOREIGN KEY (LastModifiedBy)
  REFERENCES User(UserId)
);

CREATE TABLE IF NOT EXISTS CashFLowType {
  CashFlowTypeId TINYINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Type VARCHAR(64) NOT NULL
} COMMENT 'EGRESO || INGRESO';

CREATE TABLE IF NOT EXISTS Change (
  ChangeId INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  SaleId INT UNSIGNED NOT NULL,
  CashFlowTypeId TINYINT NOT NULL,
  Total DECIMAL(20, 2) NOT NULL,
  QuantityItems MEDIUMINT UNSIGNED NOT NULL,
  Reason VARCHAR(510) NOT NULL,
  CreatedBy MEDIUMINT UNSIGNED NOT NULL,
  CreatedDate DATETIME DEFAULT NOW(),
  LastModifiedBy MEDIUMINT UNSIGNED NOT NULL,
  LastModifiedDate DATETIME NOT NULL,

  CONSTRAINT ChangeSaleFk
  FOREIGN KEY (SaleId)
  REFERENCES Sale(SaleId),

  CONSTRAINT ChangeCashFlowTypeFk
  FOREIGN KEY (CashFlowTypeId)
  REFERENCES CashFlowType(CashFlowTypeId),

  CONSTRAINT ChangeCreatedByFk
  FOREIGN KEY (CreatedBy)
  REFERENCES User(UserId),

  CONSTRAINT ChangeLastModifiedByFk
  FOREIGN KEY (LastModifiedBy)
  REFERENCES User(UserId)
) COMMENT 'Product change by other';

CREATE TABLE IF NOT EXISTS ChangeDetail (
  ChangeDetailId INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ChangeId INT UNSIGNED NOT NULL,
  ProductId INT UNSIGNED NOT NULL,
  
  CONSTRAINT ChangeDetailChangeFk
  FOREIGN KEY (ChangeId)
  REFERENCES Change(ChangeId),
  
  CONSTRAINT ChangeDetailProductFk
  FOREIGN KEY (ProductId)
  REFERENCES Product(ProductId)
);

CREATE TABLE IF NOT EXISTS CashFLow {
  CashFlowId INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CashFlowTypeId INT UNSIGNED NOT NULL,
  Quantity INT UNSIGNED NOT NULL,
  Concept VARCHAR(128) NOT NULL,
  CreatedBy MEDIUMINT UNSIGNED NOT NULL,
  CreatedDate DATETIME DEFAULT NOW(),
  LastModifiedBy MEDIUMINT UNSIGNED NOT NULL,
  LastModifiedDate DATETIME DEFAULT NOW(),

  CONSTRAINT CashflowCashFlowType
  FOREIGN KEY (CashFlowTypeId)
  REFERENCES CashFLowType(CashFlowTypeId),

  CONSTRAINT CashFLowCreatedByFk
  FOREIGN KEY (CreatedBy)
  REFERENCES User(UserId),

  CONSTRAINT CashFLowLastModifiedByFk
  FOREIGN KEY (LastModifiedBy)
  REFERENCES User(UserId)
}

CREATE TABLE IF NOT EXISTS CashLimit {
  CashLimitId INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  LimitQuantity MEDIUMINT UNSIGNED NOT NULL,
  CreatedBy MEDIUMINT UNSIGNED NOT NULL,
  CreatedDate DATETIME DEFAULT NOW(),
  LastModifiedBy MEDIUMINT UNSIGNED NOT NULL,
  LastModifiedDate DATETIME DEFAULT NOW(),

  CONSTRAINT CashLimitCreatedByFk
  FOREIGN KEY (CreatedBy)
  REFERENCES User(UserId),

  CONSTRAINT CashLimitLastModifiedByFk
  FOREIGN KEY (LastModifiedBy)
  REFERENCES User(UserId)
} COMMENT 'CASH LIMIT TO LOCK SELLS';